[package]
name = "http11_server"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = ["gzip", "br", "zstd"]
gzip = ["dep:flate2"]
br = ["dep:brotli"]
zstd = ["dep:zstd"]

[dependencies]
shiguredo_http11 = { path = "../.." }
rustls = { version = "0.23", default-features = false, features = [
    "std",
    "tls12",
    "aws-lc-rs",
] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "io-util",
    "macros",
] }
tokio-rustls = "0.26"
noargs = "0.4"

# 圧縮 (オプション)
flate2 = { version = "1", optional = true }
brotli = { version = "8", optional = true }
zstd = { version = "0.13", optional = true }
